version: '3'

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command: >
      start-dev
      --hostname-strict=false
      --hostname-strict-https=false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  backend:
    build:
      context: ./backend-springboot
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - keycloak
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
